# Generated by Django 2.1.2 on 2018-10-24 13:05

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import midas.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Query",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField()),
                ("provider", midas.models.UnboundedCharField()),
                ("endpoint", midas.models.UnboundedCharField()),
                (
                    "method",
                    midas.models.UnboundedCharField(
                        choices=[("POST", "POST"), ("PUT", "PUT"), ("DELETE", "DELETE")]
                    ),
                ),
                ("content", django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        )
    ]
