# Generated by Django 2.1.11 on 2019-09-03 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authent', '0002_auto_20190124_0928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='owner',
            field=models.UUIDField(blank=True, db_index=True, help_text='Unique identifier for the owner of the application', null=True),
        ),
    ]
