# Generated by Django 2.2 on 2019-07-03 11:30

import django.contrib.postgres.functions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("mds", "0033_post_fill_device_saved_at")]

    operations = [
        # Had to do this or Django was rejecting "TransactionNow()" as an invalid datetime
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name="device",
                    name="saved_at",
                    field=models.DateTimeField(
                        db_index=True,
                        default=django.contrib.postgres.functions.TransactionNow,
                        editable=False,
                    ),
                )
            ]
        )
    ]
