# Generated by Django 2.1.5 on 2019-10-23 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mds', '0056_post_compliance_saved_at_not_nullable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventrecord',
            name='saved_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
    ]
